site_name: Servidor Desafios

nav:
    - Home: README.md
    - Guia Do Aluno: guia_aluno.md
    - Guia Do Desenvolvedor: guia_desenvolvedor.md
    - Guia Do Professor: index.md

theme: jekyll-theme-slate