site_name: Servidor Desafios
site_url: https://sabrinasimao.github.io/softdes-desafios/
repo_url: https://sabrinasimao.github.io/softdes-desafios/

nav:
    - Home: index.md
    - Guia Do Aluno: guia_aluno.md
    - Guia Do Desenvolvedor: guia_desenvolvedor.md
    - Guia Do Professor: guia_prof.md
    - API: API.md

theme:
  name: "material"
  
plugins:
  - search
  - mkdocstrings:
      watch:
        - src