site_name: Servidor Desafios

nav:
    - Home: pagina_inicial.md
    - Guia Do Aluno: guia_aluno.md
    - Guia Do Desenvolvedor: guia_desenvolvedor.md
    - Guia Do Professor: guia_prof.md
    - API: API.md

theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - Codigo_desafios/src